### PR TITLE
Fix a bug in Windows when upload a directory.

### PR DESCRIPTION
**Pull request by IvanLuLyf**

### CODE REVIEW

**Comment by ianopolous** [comment]
Thanks for the fix!

**Comment by iamxwts** [comment]
{"Hash":"QmQiy6M9J38XhMYBpw4aLtvpTuhLaEtoBaUtFAkUUBE9KJ","Links":[],"Name":"test\\\\2.txt"}
{"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test"}
{"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test\\\\1"}
{"Hash":"QmXkQeeqoVptLAgNh5TSYHc83bbkskHBkbLUYLSZfJkTnv","Links":[],"Name":"test\\\\1.txt"}
{"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test\\\\2"}
{"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test\\\\2\\\\2.1"}
{"Hash":"QmYemFg3uZQvBMzKo1REVLJpHkNJLFhKnDSH1bK3gqJAJK","Links":[],"Name":"test\\\\2\\\\2.1\\\\2.1.1.txt"}
{"Hash":"QmZnZjR2F3nynTVo7UkPm8SJfeK5w2y1hkWshFwnyh8jcA","Links":[],"Name":"test\\\\2\\\\2.1\\\\2.1.2.txt"}
{"Hash":"QmQiy6M9J38XhMYBpw4aLtvpTuhLaEtoBaUtFAkUUBE9KJ","Links":[],"Name":"test\\\\2.txt"}

Sorry，This bug hasn't been solved.

**Comment by iamxwts** [comment]
This bug hasn't been solved. It still exists. The hash calculation of the folder is all the same. If Linux is completely OK.
{"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test"}
{"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test/1"}
{"Hash":"QmXkQeeqoVptLAgNh5TSYHc83bbkskHBkbLUYLSZfJkTnv","Links":[],"Name":"test/1.txt"}
{"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test/2"}
{"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test/2/2.1"}
{"Hash":"QmYemFg3uZQvBMzKo1REVLJpHkNJLFhKnDSH1bK3gqJAJK","Links":[],"Name":"test/2/2.1/2.1.1.txt"}
{"Hash":"QmZnZjR2F3nynTVo7UkPm8SJfeK5w2y1hkWshFwnyh8jcA","Links":[],"Name":"test/2/2.1/2.1.2.txt"}
{"Hash":"QmQiy6M9J38XhMYBpw4aLtvpTuhLaEtoBaUtFAkUUBE9KJ","Links":[],"Name":"test/2.txt"}

**Comment by IvanLuLyf** [comment]
> This bug hasn't been solved. It still exists. The hash calculation of the folder is all the same. If Linux is completely OK.
> {"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test"}
> {"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test/1"}
> {"Hash":"QmXkQeeqoVptLAgNh5TSYHc83bbkskHBkbLUYLSZfJkTnv","Links":[],"Name":"test/1.txt"}
> {"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test/2"}
> {"Hash":"QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn","Links":[],"Name":"test/2/2.1"}
> {"Hash":"QmYemFg3uZQvBMzKo1REVLJpHkNJLFhKnDSH1bK3gqJAJK","Links":[],"Name":"test/2/2.1/2.1.1.txt"}
> {"Hash":"QmZnZjR2F3nynTVo7UkPm8SJfeK5w2y1hkWshFwnyh8jcA","Links":[],"Name":"test/2/2.1/2.1.2.txt"}
> {"Hash":"QmQiy6M9J38XhMYBpw4aLtvpTuhLaEtoBaUtFAkUUBE9KJ","Links":[],"Name":"test/2.txt"}

I think you should clone this repo and build jar package by yourself.

**Comment by odisseus** [comment]
@iamxwts, try using a recent [snapshot](https://jitpack.io/docs/#snapshots) of the repository, which is built by Jitpack. It contains this pull request, which means that it should have your issue fixed.

The instructions for Maven are [here](https://jitpack.io/#ipfs/java-ipfs-http-client/). For the version number, use the short hash of the commit (e. g. `b5f6b90` for the current master).

**Pull request merged**
