### PR TITLE
Align maven coordinates with JitPack

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by tdiesler** [comment]
This likely fails because of #82

**Comment by tdiesler** [comment]
Unrelated test failure in Travis

```
Tests run: 37, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 64.958 sec <<< FAILURE! - in io.ipfs.api.APITest
swarmTest(io.ipfs.api.APITest)  Time elapsed: 0.034 sec  <<< ERROR!
java.lang.RuntimeException: 
IOException contacting IPFS daemon.
Trailer: [X-Stream-Error] {"Message":"connect QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ failure: dial attempt failed: failed to dial \u003cpeer.ID aCpDMG\u003e (default failure)","Code":0,"Type":"error"}
	at io.ipfs.api.APITest.swarmTest(APITest.java:661)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://127.0.0.1:5001/api/v0/swarm/connect?arg=/ip4/127.0.0.1/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
	at io.ipfs.api.APITest.swarmTest(APITest.java:661)
```

This occurs frequently, but not always.

**Comment by ianopolous** [comment]
I'd rather fix any problem with the original multipart implementation, if indeed there is a problem.

**Comment by tdiesler** [comment]
Failing because of #94

**Pull request merged**
