### PR TITLE
Easy run ipfs daemon with Docker Compose

### PR DESCRIPTION
**Pull request by manandbytes**

### CODE REVIEW

**Comment by ianopolous** [comment]
It would be good to include the easiest option for installing ipfs, which is to download from
https://dist.ipfs.io/#go-ipfs

**Comment by manandbytes** [comment]
> It would be good to include the easiest option for installing ipfs

I do not use this option and do not think I'm qualified enough to say anything about it.

**Comment by manandbytes** [comment]
Any updates?

**Comment by ianopolous** [comment]
I'll merge it when I have time to also add the simpler option to cover all bases.

**Pull request merged**
