### PR TITLE
NPE in simple recursive ipfs add scenario

### PR DESCRIPTION
**Pull request by tdiesler**
This PR add a test case with the two failing tests being ignored. Please note, that these tests fail frequently, but not always. I'd say if it is consistently good in Travis, its good enough.

### CODE REVIEW

**Comment by tdiesler** [comment]
Fails unrelated to this PR because of 

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by ianopolous** [comment]
Thanks! I'll have a look at this asap.

**Comment by ianopolous** [comment]
I've also pushed a fix for the npe to master, and it's given a hint as to why the multipart might be failing. I will investigate further soon.

**Comment by ianopolous** [comment]
I've also simplified the multipart implementation, but it doesn't seem to fix these tests (though it seems to reduce their failure rate)

**Comment by ianopolous** [comment]
@tdiesler can you rebase this branch of master?

**Comment by ianopolous** [comment]
I've fixed the underlying multipart bug in master. So closing this now. There was a missing http header - 
Expect: 100-continue.

**Pull request closed without merging**
