### PR TITLE
[resolves #79] Failure with recursive add with binary in sub directory

### LINKED ISSUE #79: Failure with recursive add with binary in sub directory
When adding a tree like this

```
$ ipfs add -r src/test/resources/html
added QmVts3YjmhsCSqMv8Thk1CCy1nnpCbqEFjbkjS7PEzthZE html/README.html
added QmYpbSXyiCTYCbyMpzrQNix72nBYB8WRv6i39JqRc8C1rx html/chap/ch01.html
added QmT1cVKZQPvKhS8Rg9ek7UgThwFC8gC6gAJBiRwMKMnYyg html/css/default.css
added QmaMgvGJjZU511pzH1fSwh9RRnKckyujoRxVeDSEaEGM5N html/img/logo.png
added QmeaY5WQKs3iB5UrgobERnTamHwJYMcCLRWhHK42KtVt1b html/chap
added QmfPRsChuVCsnN4PGLaDCngvjqCoc9KGkxea4hgiq6qitk html/css
added QmYhaNnLGtFDEc559T9bVkqYqaXLGojMWDzVqjFZgrmnCi html/img
added QmWVMRbFTrA6pMhsfXzsyoWqmrhy5FPd4VitfX79R5bguw html
```

I see the java client fail like this

```
java.lang.IllegalStateException: Remote IPFS error: http: invalid Read on closed Body
	at io.ipfs.api.MerkleNode.fromJSON(MerkleNode.java:74)
	at io.ipfs.api.IPFS.lambda$0(IPFS.java:91)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.ipfs.api.IPFS.add(IPFS.java:92)
	at io.ipfs.api.IPFS.add(IPFS.java:78)
	at io.ipfs.api.IPFS.add(IPFS.java:74)
	at io.ipfs.api.IPFS.add(IPFS.java:70)
	at io.ipfs.api.RecursiveAddTest.testAdd(RecursiveAddTest.java:21)
```

This is caused by `html/img/logo.png`

Here is a PR that should help to reproduce this: https://github.com/ipfs/java-ipfs-api/pull/80

### PR DESCRIPTION
**Pull request by tdiesler**
This PR replaces the existing Multipart implementation with Apache HttpClient. I believe the problem was with an incorrect implementation of chunked encoding, which is indeed not trivial to do. 

This now pulls in additional dependencies

```
[tdiesler@macbook java-ipfs-api]$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building java-ipfs-api v1.2.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ api ---
[INFO] io.ipfs:api:jar:v1.2.1-SNAPSHOT
[INFO] +- com.github.multiformats:java-multiaddr:jar:v1.3.0:compile
[INFO] |  +- com.github.multiformats:java-multibase:jar:v1.0.0:compile
[INFO] |  +- com.github.multiformats:java-multihash:jar:v1.1.0:compile
[INFO] |  \- com.github.ipld:java-cid:jar:v1.1.0:compile
[INFO] +- org.apache.httpcomponents:httpmime:jar:4.5.6:compile
[INFO] |  \- org.apache.httpcomponents:httpclient:jar:4.5.6:compile
[INFO] |     +- org.apache.httpcomponents:httpcore:jar:4.4.10:compile
[INFO] |     +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |     \- commons-codec:commons-codec:jar:1.10:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

and will likely break the non-maven build. However, it removes the maintenance cost for a correct multipart implementation and perhaps more importantly should work with very large files in directory structures.

Tested with 
```
> ipfs daemon --enable-pubsub-experiment &
> mvn clean install

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.799 sec - in io.ipfs.api.IPFSAddTest
Tests run: 36, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 21.839 sec - in io.ipfs.api.APITest
```

### CODE REVIEW

**Comment by tdiesler** [comment]
This likely fails because of #82

**Comment by tdiesler** [comment]
@ianopolous Could you please comment on this PR? It is a blocker for us and quite a substantial change.

**Comment by tdiesler** [comment]
Failing because of #94

**Comment by ianopolous** [comment]
Same as on the other pr, I'd rather not pull in apache dependencies but fix any bugs in the existing multipart implementation (especially if, as you say, it still fails with the apache version). 

If you can make a pr with a deterministic test that fails in multipart, without checking in large binaries that would be a good starting point. 

Also breaking the non maven build is not an option. I'm trying to allow support for maven out of courtesy, but I do not use maven myself.

**Comment by ianopolous** [comment]
I've added a couple of tests with random binary data, but none of them break the multipart. If you can construct a similar one that does that would be great.

**Pull request closed without merging**
