### PR TITLE
Version 1.1.1 for maven support

### PR DESCRIPTION
**Pull request by celeduc**
v1.1.0 doesn't work with maven due to broken dependencies. The included version 1.1.0 of java-multiaddr [which reports being version 1.0.0](https://github.com/multiformats/java-multiaddr#6) makes the compiled v1.0.0 not work unless the more recent multiaddr v1.0.0 is used, and this is hard to detect.

* Update README.md to show three options for use (releases, maven, build-yourself)
* Upgraded to java-multiaddr 1.1.1 for maven build to pass, and to show the correct version of [multiaddr] used
* Added Travis CI integration to improve dependency checking (could someone with Travis admin access please activate https://travis-ci.org/ipfs/java-ipfs-api ? @diasdavid )

* We'll need to cut a new release v1.1.1 for this.

### CODE REVIEW

**Comment by celeduc** [comment]
Travis terminates the virtual machine at the end of the test, so it doesn't matter what you start: it all gets thrown away.

I like the script. It'd need to be changed to add arguments, though, as the tests sometimes break unless the `--enable-pubsub-experiment` option is set.

**Comment by celeduc** [comment]
@ianopolous Could you please cut v1.1.1 for this? I don't have perms. Thanks

**Comment by ianopolous** [comment]
Done. Sorry it took so long. Been a busy week.

**Comment by celeduc** [comment]
Thank you!

**Pull request merged**
