### PR TITLE
Added more MultiAddress tests + started to make fields as more privat…

### PR DESCRIPTION
**Pull request by sic2**
…e/protected as possible

### CODE REVIEW

**Comment by ianopolous** [comment]
The fields you've made protected are the API, and hence must remain public.

**Comment by sic2** [comment]
Hi @ianopolous , thank you for your answer.

Why are you using the fields for the API? 
Should not you use getters? That will also preserve encapsulation. 

Let me know what you guys, the project admins, decide to do.

**Comment by ianopolous** [comment]
Using the fields allows us to provide a similar api to the command line Go interface, and also to the Javascript interface. It allows users to issue commands like, ipfs.refs.local(); In this case there is nothing to encapsulate, all we are exposing is the API itself. 

I'd be happy to merge the new tests, if they were on their own.

**Comment by sic2** [comment]
I will not against your design choices.

I will fix this review soon. I have been busy with other projects :)

**Pull request closed without merging**
